In [1]:
import numpy as np

In [4]:
num_test = 10
num_train = 10
dists = np.zeros((num_test, num_train))


In [6]:
for i in range(num_test):
    for j in range(num_train):
        dists[i, j] = i * j

In [8]:
print (dists)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [17]:
print (dists[2,:])
print(dists[3,:] - dists[2,:])
print((dists[3,:] - dists[2,:]) ** 2)
print(np.sum((dists[3,:] - dists[2,:]) ** 2))
np.sqrt(np.sum((dists[3,:] - dists[2,:]) ** 2))

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
285.0


16.881943016134134

In [19]:
sum = 0.0
print (sum)
print (len (dists[2,:]))

0.0
10


In [20]:
print (dists)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [43]:
print(dists[3, :] - dists)
print(np.sum((dists[3, :] - dists), axis=1))
# print (type (((dists[2, :] - dists)**2)))
# print (np.sum((dists[2, :] - dists)**2))
# dists[3, :] = np.sum((dists[2, :] - dists)**2, axis = 1)
# print (dists[3, :])

# print (np.sqrt(np.sum((dists[2, :] - dists)**2, axis = 1)))

[[ 1.14000000e+03  2.85000000e+02  0.00000000e+00  4.34559214e+68
   1.14000000e+03  2.56500000e+03  4.56000000e+03  7.12500000e+03
   1.02600000e+04  1.39650000e+04]
 [ 1.14000000e+03  2.84000000e+02 -2.00000000e+00  4.34559214e+68
   1.13600000e+03  2.56000000e+03  4.55400000e+03  7.11800000e+03
   1.02520000e+04  1.39560000e+04]
 [ 1.14000000e+03  2.83000000e+02 -4.00000000e+00  4.34559214e+68
   1.13200000e+03  2.55500000e+03  4.54800000e+03  7.11100000e+03
   1.02440000e+04  1.39470000e+04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.14000000e+03  2.81000000e+02 -8.00000000e+00  4.34559214e+68
   1.12400000e+03  2.54500000e+03  4.53600000e+03  7.09700000e+03
   1.02280000e+04  1.39290000e+04]
 [ 1.14000000e+03  2.80000000e+02 -1.00000000e+01  4.34559214e+68
   1.12000000e+03  2.54000000e+03  4.53000000e+03  7.09000000e+03
   1.02200000e+04  1.39200000e+04

In [44]:
hi = np.zeros((3,3))
print (hi)
print (type (hi))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [48]:
a =list()
print (a)
a.append(1)
print (a)
a.append(2)
print (a)

[]
[1]
[1, 2]


In [62]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

print (a.shape)
print (b.shape)
print (np.dot (a, b))
print (np.dot (a, b).shape)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]
(2, 2)


In [81]:
a = np.array ([[7],
               [2]])
print (a.shape)
b = np.array([1,2,1,2, 3,4,3,4, 5,6,5,6])
print (b.shape)
print (a+b)

abc = np.zeros ((50,500))
print (abc.shape)

(2, 1)
(12,)
[[ 8  9  8  9 10 11 10 11 12 13 12 13]
 [ 3  4  3  4  5  6  5  6  7  8  7  8]]
(50, 500)
