In [15]:
import numpy as np

In [16]:
num_test = 10
num_train = 10
dists = np.zeros((num_test, num_train))


In [17]:
for i in range(num_test):
    for j in range(num_train):
        dists[i, j] = i * j

In [18]:
print (dists)
print ()
print (dists[3,3])

a = dists[3,3] ** 2
b = dists[3,3] * dists[3,3]

print (a)
print (b)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]

9.0
81.0
81.0


In [19]:
print (dists[2,:])
print(dists[3,:] - dists[2,:])
print((dists[3,:] - dists[2,:]) ** 2)
print(np.sum((dists[3,:] - dists[2,:]) ** 2))
np.sqrt(np.sum((dists[3,:] - dists[2,:]) ** 2))

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
285.0


16.881943016134134

In [20]:
sum = 0.0
print (sum)
print (len (dists[2,:]))

0.0
10


In [21]:
print (dists)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [22]:
print(dists[3, :] - dists)
print(np.sum((dists[3, :] - dists), axis=1))
# print (type (((dists[2, :] - dists)**2)))
# print (np.sum((dists[2, :] - dists)**2))
# dists[3, :] = np.sum((dists[2, :] - dists)**2, axis = 1)
# print (dists[3, :])

# print (np.sqrt(np.sum((dists[2, :] - dists)**2, axis = 1)))

[[  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.]
 [  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9.]
 [  0.  -2.  -4.  -6.  -8. -10. -12. -14. -16. -18.]
 [  0.  -3.  -6.  -9. -12. -15. -18. -21. -24. -27.]
 [  0.  -4.  -8. -12. -16. -20. -24. -28. -32. -36.]
 [  0.  -5. -10. -15. -20. -25. -30. -35. -40. -45.]
 [  0.  -6. -12. -18. -24. -30. -36. -42. -48. -54.]]
[ 135.   90.   45.    0.  -45.  -90. -135. -180. -225. -270.]


In [23]:
hi = np.zeros((3,3))
print (hi)
print (type (hi))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [24]:
a =list()
print (a)
a.append(1)
print (a)
a.append(2)
print (a)

[]
[1]
[1, 2]


In [25]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

print (a.shape)
print (b.shape)
print (np.dot (a, b))
print (np.dot (a, b).shape)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]
(2, 2)


In [26]:
a = np.array ([[7],
               [2]])
print (a.shape)
b = np.array([1,2,1,2, 3,4,3,4, 5,6,5,6])
print (b.shape)
print (a+b)

abc = np.zeros ((50,500))
print (abc.shape)

(2, 1)
(12,)
[[ 8  9  8  9 10 11 10 11 12 13 12 13]
 [ 3  4  3  4  5  6  5  6  7  8  7  8]]
(50, 500)


In [27]:
a = 0
b = 3.0
c = max (a, b)
print (c)

3.0


In [64]:
a = np.array([[1,2],
              [3,4],
              [5,6]])
b = np.array([1,2,3])
print (a.shape)
print (b.shape)
print (b[...,np.newaxis].shape)
print (b)
print (a)
print (b[...,np.newaxis])

c = a - b[...,np.newaxis]
print ("c.shape: ", c.shape)
print (c)

d = a / b[...,np.newaxis]
print ("d.shape: ", d.shape)
print (d)

(3, 2)
(3,)
(3, 1)
[1 2 3]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]]
c.shape:  (3, 2)
[[0 1]
 [1 2]
 [2 3]]
d.shape:  (3, 2)
[[1.         2.        ]
 [1.5        2.        ]
 [1.66666667 2.        ]]


In [69]:
import itertools

a = np.array([[[1,2],
              [3,4],
              [5,6]],
            [[7,8],
              [9,0],
              [1,2]]])
# a_list = list (a)
print (a.shape)
aa = []
for i in range (a.shape[0]):
  aa.append ( list (itertools.chain (*a[i])) )
aa = np.array (aa)
print (aa)
print (aa.shape)

print ()

b = np.array([ [[[1,2],
              [3,4],
              [5,6]],
            [[7,8],
              [9,0],
              [1,2]]],
              
              [[[11,22],
              [33,44],
              [55,66]],
            [[77,88],
              [99,0],
              [11,22]]] ])

print (b.shape)

bb = []
for i in range (b.shape[0]):

  tmp = []
  for j in range (b.shape[1]):
    tmp.append ( list (itertools.chain (*b[i][j])) )
  tmp = np.array (tmp)
  print ("tmp: ", tmp)

  bb.append ( list (itertools.chain (*tmp)) )
bb = np.array (bb)
print ("bb: ", bb)
print (bb.shape)

print ()
print ("------------")
print (bb[1][1])
print (bb[1,1])

# b = np.array([[1,2],
#       [3,4],
#       [5,6]])
# bb = list (itertools.chain (*b))
# print (b)
# print (bb)


(2, 3, 2)
[[1 2 3 4 5 6]
 [7 8 9 0 1 2]]
(2, 6)

(2, 2, 3, 2)
tmp:  [[1 2 3 4 5 6]
 [7 8 9 0 1 2]]
tmp:  [[11 22 33 44 55 66]
 [77 88 99  0 11 22]]
bb:  [[ 1  2  3  4  5  6  7  8  9  0  1  2]
 [11 22 33 44 55 66 77 88 99  0 11 22]]
(2, 12)

------------
22
22
