In [48]:
import random

seq = [1, 2, 3, 4, 5]
random_choice = random.choice(seq)
print(random_choice)
random_choices = random.sample(seq, 3)
print(random_choices)
random_choicess = random.choices(seq, k=3)
print(random_choicess)

import numpy as np
rr = np.array (random_choicess)
print (rr)

5
[3, 5, 2]
[2, 5, 2]
[2 5 2]


In [1]:
import numpy as np

aa = np.array ([1,2,3,4,5])
bb = np.random.choice (aa, 2)
print (bb)
print (type(bb))

[3 4]
<class 'numpy.ndarray'>


In [3]:
aaa = np.zeros ([3])
print (aaa)

bbb = np.ones ([3,1])
print (bbb)

[0. 0. 0.]
[[1.]
 [1.]
 [1.]]
