In [1]:
import random

seq = [1, 2, 3, 4, 5]
random_choice = random.choice(seq)
print(random_choice)
random_choices = random.sample(seq, 3)
print(random_choices)
random_choicess = random.choices(seq, k=3)
print(random_choicess)

import numpy as np
rr = np.array (random_choicess)
print (rr)

1
[3, 2, 1]
[4, 1, 5]
[4 1 5]


In [2]:
import numpy as np

aa = np.array ([1,2,3,4,5])
bb = np.random.choice (aa, 2)
print (bb)
print (type(bb))

[2 1]
<class 'numpy.ndarray'>


In [3]:
aaa = np.zeros ([3])
print (aaa)

bbb = np.ones ([3,1])
print (bbb)

[0. 0. 0.]
[[1.]
 [1.]
 [1.]]


In [37]:
hidden_dim = 50
input_dim = 5
W1_list=[[random.normalvariate(mu=0.0, sigma=0.001) for j in range(hidden_dim)] for i in range(input_dim)]

w1 = [ [random.normalvariate (mu=0.0, sigma=0.001) for col in range(hidden_dim)] for row in range(input_dim) ]

print (np.array (W1_list)[0:3,0:3])
print (np.array (w1)[0:3,0:3])

[[-3.41339847e-04 -5.49263414e-04  4.60985500e-04]
 [-6.66209417e-04  3.92992901e-04 -5.40375720e-04]
 [-2.73306174e-05  4.54191271e-04  3.50897312e-04]]
[[-0.00030358 -0.00034352  0.00124368]
 [ 0.00179329 -0.00038829 -0.00073022]
 [-0.0025359   0.00018277 -0.00079418]]


In [42]:
b1 = [0.0 for col in range(hidden_dim)]
print (b1)
print (np.array(b1).shape)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
(50,)
