In [1]:
import numpy as np

In [2]:
num_test = 10
num_train = 10
dists = np.zeros((num_test, num_train))


In [3]:
for i in range(num_test):
    for j in range(num_train):
        dists[i, j] = i * j

In [16]:
print (dists)
print ()
print (dists[3,3])

a = dists[3,3] ** 2
b = dists[3,3] * dists[3,3]

print (a)
print (b)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]

9.0
81.0
81.0


In [5]:
print (dists[2,:])
print(dists[3,:] - dists[2,:])
print((dists[3,:] - dists[2,:]) ** 2)
print(np.sum((dists[3,:] - dists[2,:]) ** 2))
np.sqrt(np.sum((dists[3,:] - dists[2,:]) ** 2))

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
285.0


16.881943016134134

In [6]:
sum = 0.0
print (sum)
print (len (dists[2,:]))

0.0
10


In [7]:
print (dists)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [8]:
print(dists[3, :] - dists)
print(np.sum((dists[3, :] - dists), axis=1))
# print (type (((dists[2, :] - dists)**2)))
# print (np.sum((dists[2, :] - dists)**2))
# dists[3, :] = np.sum((dists[2, :] - dists)**2, axis = 1)
# print (dists[3, :])

# print (np.sqrt(np.sum((dists[2, :] - dists)**2, axis = 1)))

[[  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.]
 [  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9.]
 [  0.  -2.  -4.  -6.  -8. -10. -12. -14. -16. -18.]
 [  0.  -3.  -6.  -9. -12. -15. -18. -21. -24. -27.]
 [  0.  -4.  -8. -12. -16. -20. -24. -28. -32. -36.]
 [  0.  -5. -10. -15. -20. -25. -30. -35. -40. -45.]
 [  0.  -6. -12. -18. -24. -30. -36. -42. -48. -54.]]
[ 135.   90.   45.    0.  -45.  -90. -135. -180. -225. -270.]


In [9]:
hi = np.zeros((3,3))
print (hi)
print (type (hi))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [10]:
a =list()
print (a)
a.append(1)
print (a)
a.append(2)
print (a)

[]
[1]
[1, 2]


In [11]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

print (a.shape)
print (b.shape)
print (np.dot (a, b))
print (np.dot (a, b).shape)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]
(2, 2)


In [12]:
a = np.array ([[7],
               [2]])
print (a.shape)
b = np.array([1,2,1,2, 3,4,3,4, 5,6,5,6])
print (b.shape)
print (a+b)

abc = np.zeros ((50,500))
print (abc.shape)

(2, 1)
(12,)
[[ 8  9  8  9 10 11 10 11 12 13 12 13]
 [ 3  4  3  4  5  6  5  6  7  8  7  8]]
(50, 500)


In [13]:
a = 0
b = 3.0
c = max (a, b)
print (c)

3.0


In [14]:
a = np.array([[1,2],
              [3,4],
              [5,6]])
b = np.array([1,2,3])
print (a.shape)
print (b.shape)
print (b[...,np.newaxis].shape)
print (b)
print (a)
print (b[...,np.newaxis])

c = a - b[...,np.newaxis]
print ("c.shape: ", c.shape)
print (c)

d = a / b[...,np.newaxis]
print ("d.shape: ", d.shape)
print (d)

(3, 2)
(3,)
(3, 1)
[1 2 3]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]]
c.shape:  (3, 2)
[[0 1]
 [1 2]
 [2 3]]
d.shape:  (3, 2)
[[1.         2.        ]
 [1.5        2.        ]
 [1.66666667 2.        ]]
